### ISSUE TITLE
Updated multiple bitstring tracking causes errors in sampling expectation values

### ISSUE THREAD

**Issue by asciineuron** [asciineuron/bgls#27]
## Description

First I changed `needs_trajectories` to return _True_ if not using `act_on` (this was a bug, so act_on_near_clifford wasn't properly parallelized).

However, doing so causes issues when comparing expectation values in the test suite. On the one hand, randomization between parallelized and non-parallelized circuits won't match (since the new dictionary structure of bitstring:count isn't a linear list of experiments like before). I think this may be the cause, but I am not sure.

**Comment by asciineuron** [comment]
@rmlarose I will have to check this out more, but I noticed this while making some updates.

**Comment by asciineuron** [comment]
@rmlarose I will have to check this out more, but I noticed this while making some updates.

**Comment by rmlarose** [comment]
Please do add more details and a minimal example which exhibits the behavior

**Comment by asciineuron** [comment]
Looking at your expectation sampling tests in the branch we just merged, I think the problem was just tolerance/#-samples. I had been using `tol=1e-2 ` vs your `tol=1e-1`, and increasing to a very large number of samples with a smaller circuit fixed it. 
I guess it's just not ideal for proving functional equivalence
