### ISSUE TITLE
Incorrect two-qubit gate application in custom states doc

### ISSUE THREAD

**Issue by rmlarose** [asciineuron/bgls#33]
@asciineuron there's a bug in the custom simulator of the custom (third party) states doc. You can see on the current docs page the sampled bitstrings for the GHZ circuit at the end are incorrect. While cleaning up this doc in #32 I noticed this and narrowed the bug down to applying two-qubit gates.

![image](https://github.com/asciineuron/bgls/assets/32416820/60e0b598-c743-4036-8d94-96ed9d8a75a0)

Could you PTAL?

**Comment by asciineuron** [comment]
@rmlarose Got this fixed on #32 - it was just because I originally referred to indices in the opposite manner as cirq, so we just had to reverse the target bit ordering.
