### ISSUE TITLE
Add arXiv and journal ref + citation

### ISSUE THREAD

**Issue by rmlarose** [asciineuron/bgls#48]
For arXiv let's add a badge similar to https://github.com/unitaryfund/mitiq#. Add a citation.bib file similar to https://github.com/unitaryfund/mitiq/blob/master/CITATION.bib with the citation info. Also add a citation section to the README which links to this file.

Links:

- https://arxiv.org/abs/2311.11787
- https://dl.acm.org/doi/10.1145/3624062.3624215

**Comment by chiragbhansali** [comment]
I can do this

**Comment by chiragbhansali** [comment]
I can do this

**Comment by rmlarose** [comment]
Closed by #51
